services:
  postgres:
    image: postgres:16
    container_name: container_name
    restart: always
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - "port:port"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U libraryuser -d librarydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  assignment_api:
    build: .
    container_name: assignment_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_HOST: POSTGRES_HOST
      POSTGRES_PORT: POSTGRES_PORT
      DATABASE_URL: "postgresql://POSTGRES_USER:POSTGRES_PASSWORD@POSTGRES_HOST:POSTGRES_PORT/POSTGRES_DB"
    ports:
      - "8000:8000"

volumes:
  postgres_data:
